name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # the GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=12 --max-line-length=127 --statistics --exit-zero
    - name: Run unittests
      run: |
        python tests.py
    - name: Download Fairy-Stockfish
      run: |
        curl -Lo fairy-stockfish https://github.com/ianfab/Fairy-Stockfish/releases/latest/download/fairy-stockfish-largeboard_x86-64
        chmod +x fairy-stockfish
    - name: Run generator.py
      run: |
        python generator.py -e ./fairy-stockfish -c 500 > test.fen
    - name: Run puzzler.py
      run: |
        python puzzler.py -e ./fairy-stockfish -d 6 test.fen > test.epd
    - name: Run pgn.py
      run: |
        python pgn.py test.epd
